/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sikuli.basics;

import java.awt.Color;

/**
 *
 * @author rhocke
 */
public class SetUpSelect extends javax.swing.JPanel {
  
  /**
   * Creates new form SetUpSelect
   */
  public SetUpSelect() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    jLabel2 = new javax.swing.JLabel();
    suSystem = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    suJava = new javax.swing.JLabel();
    suRC3 = new javax.swing.JLabel();
    jSeparator2 = new javax.swing.JSeparator();
    jLabel4 = new javax.swing.JLabel();
    suFolder = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jSeparator4 = new javax.swing.JSeparator();
    jSeparator5 = new javax.swing.JSeparator();
    option1 = new javax.swing.JCheckBox();
    option4 = new javax.swing.JCheckBox();
    option3 = new javax.swing.JCheckBox();
    option2 = new javax.swing.JCheckBox();
    jSeparator6 = new javax.swing.JSeparator();
    ask1 = new javax.swing.JButton();
    ask2 = new javax.swing.JButton();
    ask3 = new javax.swing.JButton();
    ask4 = new javax.swing.JButton();
    setupNow = new javax.swing.JButton();

    jLabel1.setText("SikuliX 1.0.1 SetUp");
    jLabel1.setAlignmentX(0.5F);

    jLabel2.setText("We are running on: ");

    suSystem.setText("...");

    jLabel3.setText("... using this Java: ");

    suJava.setText("...");

    suRC3.setText("...");

    jLabel4.setText("... in this folder");

    suFolder.setText("...");

    jLabel5.setText("Please check the appropriate options below:   (click the [ ? ] buttons to get more specific information about the option)");

    option1.setText("I want to use all options: Sikuli IDE, running scripts from commandline (and optionally Java developement)");

    option4.setText("I only want to develop in Java or Jython using NetBeans, Eclipse or other IDE's (I do not need the Sikuli IDE)");
    option4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        option4ActionPerformed(evt);
      }
    });

    option3.setText("Additionally I want to develop and run scripts in Jython language using NetBeans, Eclipse or any other IDE or script editor");
    option3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        option3ActionPerformed(evt);
      }
    });

    option2.setText("I want to run Sikuli scripts from command line (I do not need the Sikuli IDE)");
    option2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        option2ActionPerformed(evt);
      }
    });

    ask1.setText("?");
    ask1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ask1ActionPerformed(evt);
      }
    });

    ask2.setText("?");
    ask2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ask2ActionPerformed(evt);
      }
    });

    ask3.setText("?");
    ask3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ask3ActionPerformed(evt);
      }
    });

    ask4.setText("?");
    ask4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ask4ActionPerformed(evt);
      }
    });

    setupNow.setText("Setup Now");
    setupNow.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        setupNowActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jSeparator6)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jSeparator1)
          .add(jSeparator2)
          .add(jSeparator5)
          .add(layout.createSequentialGroup()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(jLabel1)
              .add(layout.createSequentialGroup()
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                  .add(layout.createSequentialGroup()
                    .add(jLabel2)
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                    .add(suSystem))
                  .add(suRC3)
                  .add(layout.createSequentialGroup()
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                      .add(jLabel3)
                      .add(jLabel4))
                    .add(18, 18, 18)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                      .add(suFolder)
                      .add(suJava)))))
              .add(jLabel5))
            .add(0, 0, Short.MAX_VALUE))
          .add(layout.createSequentialGroup()
            .add(option1)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(ask1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(layout.createSequentialGroup()
            .add(option2)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(ask2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(layout.createSequentialGroup()
            .add(option3)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 35, Short.MAX_VALUE)
            .add(ask3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(layout.createSequentialGroup()
            .add(option4)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(ask4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
            .add(0, 0, Short.MAX_VALUE)
            .add(setupNow)))
        .addContainerGap())
      .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(layout.createSequentialGroup()
          .addContainerGap()
          .add(jSeparator4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
          .addContainerGap()))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(jLabel1)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel2)
          .add(suSystem))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel4)
          .add(suFolder))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(suJava)
          .add(jLabel3))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
        .add(suRC3)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
        .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(18, 18, 18)
        .add(jLabel5)
        .add(18, 18, 18)
        .add(jSeparator5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(18, 18, 18)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(option1)
          .add(ask1))
        .add(18, 18, 18)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(option2)
          .add(ask2))
        .add(18, 18, 18)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(option3)
          .add(ask3))
        .add(18, 18, 18)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(option4)
          .add(ask4))
        .add(18, 18, 18)
        .add(jSeparator6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(18, 18, 18)
        .add(setupNow)
        .addContainerGap(16, Short.MAX_VALUE))
      .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(layout.createSequentialGroup()
          .add(172, 172, 172)
          .add(jSeparator4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .addContainerGap(331, Short.MAX_VALUE)))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void option4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option4ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_option4ActionPerformed

  private void option3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option3ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_option3ActionPerformed

  private void option2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_option2ActionPerformed

  private void ask1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ask1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_ask1ActionPerformed

  private void ask2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ask2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_ask2ActionPerformed

  private void ask3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ask3ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_ask3ActionPerformed

  private void ask4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ask4ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_ask4ActionPerformed

  private void setupNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setupNowActionPerformed
    //RunSetup.popError("setup now was clicked");
    setBackground(Color.YELLOW);
  }//GEN-LAST:event_setupNowActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton ask1;
  public javax.swing.JButton ask2;
  public javax.swing.JButton ask3;
  public javax.swing.JButton ask4;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JSeparator jSeparator4;
  private javax.swing.JSeparator jSeparator5;
  private javax.swing.JSeparator jSeparator6;
  protected javax.swing.JCheckBox option1;
  protected javax.swing.JCheckBox option2;
  protected javax.swing.JCheckBox option3;
  protected javax.swing.JCheckBox option4;
  private javax.swing.JButton setupNow;
  public javax.swing.JLabel suFolder;
  protected javax.swing.JLabel suJava;
  public javax.swing.JLabel suRC3;
  protected javax.swing.JLabel suSystem;
  // End of variables declaration//GEN-END:variables
}
