#!/bin/sh
JAVA=X
PROPS='-Xmx512M -Dfile.encoding=UTF-8 -Dsikuli.FromCommandLine'

if [ "$JAVA_HOME" != "" ]; then
  JAVABIN=$JAVA_HOME/bin
fi

if [ "$SIKULIX_HOME" != "" ]; then
  echo "SIKULIX_HOME in environment specified as "$SIKULIX_HOME
  shome=$SIKULI_HOME
else
  shome=`dirname $0`
fi

export SIKULI_COMMAND=$*
echo "running SikuliX-Script: $PROPS $CONSOLE"
echo "-jar $shome/sikuli-script.jar $SIKULI_COMMAND"
"$JAVABIN/java" $PROPS -jar "$shome/sikuli-ide.jar" $SIKULI_COMMAND

